### ISSUE TITLE
【開発】dockerコンテナ内にサウンドをマウント

### ISSUE THREAD

**Issue by YuukiReiya** [YuukiReiya/pygame#3]
https://qiita.com/Mco7777/items/18e29b98ddbc2614169b

# やること

### ホストOS側

pluseaudioのインストール
```rb
$ brew install pulseaudio
```

起動(デーモン)
```rb
$ pulseaudio --load=module-native-protocol-tcp --exit-idle-time=-1 --daemon
```

動作確認
```rb
$ pulseaudio --check -v
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
I: [] main.c: Daemon running as PID 1747
```

### コンテナ

Dockerfile
```yaml
apt-get install -y pulseaudio
```

docker-compose
>環境変数PULSE_SERVERにdocker.for.mac.localhostを設定し、
ホストMacの~/.config/pulseをDocker内のユーザーディレクトリ/root/.config/pulse(rootユーザーの場合)にバインドする
```
version: "3.3"
services:
  service_name:
    build: .
    environment:
      - PULSE_SERVER=docker.for.mac.localhost
    volumes:
      - type: bind
        source: ~/.config/pulse
        target: /root/.config/pulse
```
